---
- name: Configure switches
  hosts: switches
  gather_facts: no
  connection: local
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_user: ansible
    ansible_password: ansible
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: enansible
    ansible_network_os: ios
    allowed_vlans: []
    global_vlans:
    - { name: MGMT1201, id: 1201, subnet: 10.100.201.0/24, mask: 255.255.255.0, tagged: true, vswitch: vSwitch0, mgmt: true }
    - { name: LAN1101, id: 1101, subnet: 10.100.101.0/24, mask: 255.255.255.0, tagged: true, vswitch: vSwitch0, mgmt: false }
    - { name: LAN1102, id: 1102, subnet: 10.100.102.0/24, mask: 255.255.255.0, tagged: true, vswitch: vSwitch0, mgmt: false }
    - { name: DMZ1103, id: 1103, subnet: 10.100.103.0/24, mask: 255.255.255.0, tagged: true, vswitch: vSwitch0, mgmt: false }
    - { name: WAN, id: 400, subnet: 192.168.122.0/24, mask: 255.255.255.0, tagged: false, vswitch: "", mgmt: false }
    - { name: LINKNET, id: 500, subnet: 10.100.251.0/24, mask: 255.255.255.0, tagged: false, vswitch: "", mgmt: false }
    sw1_switch_ports_all: [ 0/0,0/1,0/2,0/3,1/0,1/1,1/2,1/3,2/0,2/1,2/2,2/3,3/0,3/1,3/2,3/3 ]
    sw2_switch_ports_all: [ 0/0,0/1,0/2,0/3,1/0,1/1,1/2,1/3,2/0,2/1,2/2,2/3,3/0,3/1,3/2,3/3 ]
    sw3_switch_ports_all: [ 0/0,0/1,0/2,0/3,1/0,1/1,1/2,1/3,2/0,2/1,2/2,2/3,3/0,3/1,3/2,3/3 ]
    sw4_switch_ports_all: [ 0/0,0/1,0/2,0/3,1/0,1/1,1/2,1/3,2/0,2/1,2/2,2/3,3/0,3/1,3/2,3/3 ]
    sw1_switch_interface_prefix: GigabitEthernet
    sw2_switch_interface_prefix: GigabitEthernet
    sw3_switch_interface_prefix: GigabitEthernet
    sw4_switch_interface_prefix: GigabitEthernet
    tagged_base_commands: [ "switchport trunk encapsulation dot1q", "switchport mode trunk", "switchport trunk allowed vlan {{ global_vlans | join(',') }}" ]
    untagged_base_commands: [ "no switchport trunk allowed vlan", "no switchport mode trunk", "no switchport trunk encapsulation", "switchport mode access" ]
    sw1_interfaces:
    - { mode: tagged, int: 0/0, vlan: "", desc: "SW2 HSRP", commands: [ "negotiation auto" ] }
    - { mode: custom, int: 0/1, vlan: "", desc: "", commands: [ "description FW LAN", "switchport trunk encapsulation dot1q", "switchport mode trunk", "switchport trunk allowed vlan 500,1201" ] }
    - { mode: adminshut, int: 0/2, vlan: "", desc: "", commands: }
    - { mode: adminshut, int: 0/3, vlan: "", desc: "", commands: "" }
    - { mode: untagged, int: 1/0, vlan: 400, desc: "Firewall WAN", commands: [ "negotiation auto" ] }
    - { mode: untagged, int: 1/1, vlan: 1201, desc: "Ansible", commands: [ "negotiation auto" ] }
    - { mode: adminshut, int: 1/2, vlan: "", desc: "", commands: }
    - { mode: adminshut, int: 1/3, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 2/0, vlan: "", desc: "", commands: }
    - { mode: tagged, int: 2/1, vlan: "", desc: "SW3", commands: [ "negotiation auto" ] }
    - { mode: adminshut, int: 2/2, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 2/3, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 3/0, vlan: "", desc: "", commands: "" }
    - { mode: tagged, int: 3/1, vlan: "", desc: "SW4", commands: [ "negotiation auto" ] }
    - { mode: adminshut, int: 3/2, vlan: "", desc: "", commands: "" }
    - { mode: untagged, int: 3/3, vlan: 400, desc: "Operator", commands: [ "negotiation auto" ] }
    sw2_interfaces:
    - { mode: tagged, int: 0/0, vlan: "", desc: "SW2 HSRP"}
    - { mode: custom, int: 0/1, vlan: "", desc: "", commands: [ "description FW LAN", "switchport trunk encapsulation dot1q", "switchport mode trunk", "switchport trunk allowed vlan 500,1201" ] }
    - { mode: adminshut, int: 0/2, vlan: "", desc: "", commands: }
    - { mode: adminshut, int: 0/3, vlan: "", desc: "", commands: "" }
    - { mode: untagged, int: 1/0, vlan: 400, desc: "Firewall WAN" }
    - { mode: adminshut, int: 1/1, vlan: "", desc: "", commands: }
    - { mode: untagged, int: 1/2, vlan: 1201, desc: "Ansible" }
    - { mode: adminshut, int: 1/3, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 2/0, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 2/1, vlan: "", desc: "", commands: "" }
    - { mode: tagged, int: 2/2, vlan: "", desc: "SW3"}
    - { mode: adminshut, int: 2/3, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 3/0, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 3/1, vlan: "", desc: "", commands: "" }
    - { mode: tagged, int: 3/2, vlan: "", desc: "SW4"}
    - { mode: untagged, int: 3/3, vlan: 400, desc: "Operator" }
    sw3_interfaces:
    - { mode: adminshut, int: 0/0, vlan: "", desc: "", commands: "" }
    - { mode: tagged, int: 0/1, vlan: "", desc: "ESXI1"}
    - { mode: tagged, int: 0/2, vlan: "", desc: "NetApp"}
    - { mode: tagged, int: 0/3, vlan: "", desc: "Backup"}
    - { mode: adminshut, int: 1/0, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 1/1, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 1/2, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 1/3, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 2/0, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 2/1, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 2/2, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 2/3, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 3/0, vlan: "", desc: "", commands: "" }
    - { mode: tagged, int: 3/1, vlan: "", desc: "SW1"}
    - { mode: tagged, int: 3/2, vlan: "", desc: "SW2"}
    - { mode: adminshut, int: 3/3, vlan: "", desc: "", commands: "" }
    sw4_interfaces: 
    - { mode: adminshut, int: 0/0, vlan: "", desc: "", commands: "" }
    - { mode: tagged, int: 0/1, vlan: "", desc: "ESXI1"}
    - { mode: tagged, int: 0/2, vlan: "", desc: "NetApp"}
    - { mode: tagged, int: 0/3, vlan: "", desc: "Backup"}
    - { mode: adminshut, int: 1/0, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 1/1, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 1/2, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 1/3, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 2/0, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 2/1, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 2/2, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 2/3, vlan: "", desc: "", commands: "" }
    - { mode: adminshut, int: 3/0, vlan: "", desc: "", commands: "" }
    - { mode: tagged, int: 3/1, vlan: "", desc: "SW1"}
    - { mode: tagged, int: 3/2, vlan: "", desc: "SW2"}
    - { mode: adminshut, int: 3/3, vlan: "", desc: "", commands: "" }
  tasks:
  - name: Construct list of allowed vlans
    set_fact:
      allowed_vlans: "{{ allowed_vlans + [ item.id ] }}"
    loop: "{{ global_vlans }}"
    when: "{{ item.tagged }} == true"

  # - name: Configure access ports
    # cisco.ios.ios_config:
      # parents: interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.int }}
      # lines: "{{ untagged_base_commands }} + [ switchport access vlan {{ item.vlan }}, description {{ item.desc }} ] + {{ item.commands }}"
    # notify: "Write Config"
    # loop: "{{ vars[ inventory_hostname+'_interfaces' ] }}"
    # when: ("{{ item.mode }}" == "untagged")

  - name: Configure access ports
    ios_config:
      parents: interface {{ item.int }}  
      lines:
      - switchport mode access
      - description {{ item.desc }}
      # - "{{ item.commands }}"
    notify: "Write Config"
    loop: "{{ sw1_interfaces }}"
    when: ("{{ item.mode }}" == "untagged")

  - name: Configure trunk ports
    cisco.ios.ios_config:
      parents: interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.int }}
      lines: "{{ tagged_base_commands }} + [ description {{ item.desc }} ] + {{ item.commands }}"
    notify: "Write Config"
    loop: "{{ vars[ inventory_hostname+'_interfaces' ] }}"
    when: ("{{ item.mode }}" == "tagged")

  - name: Configure custom ports
    cisco.ios.ios_config:
      parents: interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.int }}
      lines: "{{ item.commands }}"
    notify: "Write Config"
    loop: "{{ vars[ inventory_hostname+'_interfaces' ] }}"
    when: ("{{ item.mode }}" == "custom")

  - name: Admin shut interface
    cisco.ios.ios_config:
      parents: interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item }}
      lines:
      - description admin shut
      - no switchport mode
      - no switchport trunk allowed vlan
      - no switchport trunk encapsulation
      - shutdown
    notify: "Write Config"
    loop: "{{ vars[ inventory_hostname+'_interfaces' ] }}"
    when: ("{{ item.mode }}" == "adminshut")

  handlers:
  - name: Write Config
    cisco.ios.ios_command:
      commands:
      - write
