---
- name: Create one or multiple VLANs 
  hosts: all
  gather_facts: false
  connection: local
  tasks:
  - name: Run vlan command 
    cisco.ios.ios_vlans:
      config:
      - name {{ item.name }}
      - vlan_id {{ item.vlan }}
    loop: "{{ ios_vlans | dict2items }}"

