---
- name: Create one or multiple VLANs 
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  connection: local
  tasks:
  - name: Create VLAN
    cisco.ios.ios_vlans:
      config: "{{ ios_vlans }}" 
  - name: Write Config
    cisco.ios.ios_config:
      lines:
      - do copy run start

