---
- name: Configure L2 ports
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  connection: local
  vars:
    allowed_vlans: []
    tagged_vlans: "{{ ios_vlans | selectattr('tagged','==', true ) }}"
  tasks:
  - name: Configure trunk ports
    cisco.ios.ios_l2_interfaces:
      config:
      - name: "{{ ios_l2_port_type}}{{ item.port }}"
        trunk:
          allowed_vlans: "{{ allowed_vlans }}"
          encapsulation: dot1q
      state: replaced
    when: inventory_hostname == "{{ item.switch }}"
    loop: "{{ ios_l2_trunk_ports }}"
    notify: "Write Config"

  - name: Configure access ports
    cisco.ios.ios_l2_interfaces:
      config:
      - name: "{{ ios_l2_port_type}}{{ item.port }}"
        mode: access
        access:
          vlan: "{{ item.vlan }}"
    when: inventory_hostname == "{{ item.switch }}"
    loop: "{{ ios_l2_access_ports }}"
    notify: "Write Config"

  handlers:
  - name: Write Config
    cisco.ios.ios_command:
      commands:
      - write
