---
- name: Create one or multiple VLAN interfaces
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  connection: local
  tasks:
  - name: Create VLAN interface
    cisco.ios.ios_config:
      lines:
      - inerface "{{ item.name }}"
      - ip address "{{ item.ip }}"
    when: "{{ item.switch }} in inventory_hostname"  
    loop: "{{ ios_vlan_interfaces }}"
