---
- name: Create one or multiple VLAN interfaces
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  connection: local
  tasks:
  - name: Create VLAN interface
    cisco.ios.ios_config:
      lines:
      - ip address {{ item.ip }}
      parents: interface {{ item.name }}
    when: inventory_hostname == "{{ item.switch }}"
    loop: "{{ ios_vlan_interfaces }}"
