# Please see vars.yml for a valid configuration.
# Variables:
# - global_vlans:
#   - this is a dictionary that provides the following values: 
#     - id 
#     - name
---
- name: Create one or multiple VLANs 
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  connection: local
  tasks:
  - name: Create VLAN
    cisco.ios.ios_config:
      lines:
      - name {{ item.name }}
      parents:
      - vlan {{ item.id }}
    loop: "{{ global_vlans }}"
    notify: "Write Config"

  handlers:
  - name: Write Config
    cisco.ios.ios_command:
      commands:
      - write

