---
- name: Configure switches
  hosts: all
  gather_facts: no
  connection: local
  vars_files: tmpvars.yml
  vars:
    allowed_vlans: []
  tasks:
    - name: Construct list of allowed vlans
      set_fact:
        allowed_vlans: "{{ allowed_vlans + [ item.id ] }}"
      loop: "{{ global_vlans | selectattr('tagged','==',true) | list }}"

    - name: Configure access ports
      ios_config:
        lines:
          - "switchport mode access"
          - "switchport access vlan {{ item.1.vlan }}"
          - "description {{ item.1.desc }}"
        parents: "interface GigabitEthernet{{ item.0 }}"
      notify: "Write Config"
      loop: "{{ access_ports[ inventory_hostname ].items() }}"

    - name: Configure trunk ports
      ios_config:
        lines:
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
          - "switchport trunk allowed vlan {{ allowed_vlans | join(',') }}"
          - "description {{ item.1 }}"
        parents: "interface GigabitEthernet{{ item.0 }}"
      notify: "Write Config"
      loop: "{{ trunk_ports[inventory_hostname] }}"

    - name: Configure custom ports
      ios_config:
        lines: "{{ item.1.commands }}"
        parents: "interface GigabitEthernet{{ item.0 }}"
      notify: "Write Config"
      loop: "{{ custom_ports[inventory_hostname].items() }}"

  handlers:
  - name: Write Config
    cisco.ios.ios_command:
      commands:
      - write
