---
- name: Configure L2 interfaces on IOS switches
  hosts: all
  vars_files: ios_vars.yml
  gather_facts: false
  connection: local
  tasks:
  tasks:
  - name: Construct list of allowed vlans
    set_fact:
      global_allowed_vlans: "{{ global_allowed_vlans + [ item.id ] }}"
    loop: "{{ global_tagged_vlans }}"
   
  - name: Configure interface as trunk
    cisco.ios.ios_config:
      parents: interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.name }}
      lines: 
      - switchport trunk encapsulation dot1q
      - switchport mode trunk
      - switchport trunk allowed vlan {{ global_allowed_vlans | join(',') }}
      - no shutdown
    notify: "Write Config"
    loop: "{{ sw_tagged_ports }}"
 
  - name: Configure interface as access port
    cisco.ios.ios_config:
      parents: interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.name }}
      lines:
      - no switchport trunk allowed vlan
      - no switchport mode trunk
      - no switchport trunk encapsulation
      - switchport mode access
      - "{{ item.port_conf[0] }}"
      - no shutdown
    notify: "Write Config"
    loop: "{{ sw_untagged_ports }}"

  - name: Admin shut interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.name }}
    cisco.ios.ios_config:
      parents: interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.name }}
      lines:
      - description admin shut 
      - shutdown
    notify: "Write Config"
    loop: "{{ vars[ inventory_hostname+'_switch_ports_all' ] | difference(vars[ inventory_hostname+'_used_ports' ]) }}"

  handlers: 
  - name: Write Config
    cisco.ios.ios_command:
      commands:
      - write

