---
- name: Configure L2 interfaces on IOS switches
  hosts: all
  vars_files: ios_vars.yml
  gather_facts: false
  connection: local
  vars:
    local_tagged_ports: "{{ vars[ inventory_hostname+'_tagged_ports' ] }}"
    local_untagged_ports: "{{ vars[ inventory_hostname+'_untagged_ports' ] }}"
  tasks:
  # - name: Configure interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.name }} as trunk
    # cisco.ios.ios_config:
      # parents: interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.name }}
      # lines: "{{ global_tagged_port_conf }} + {{ item.port_conf + [ item.desc ] }}"
    # notify: "Write Config"
    # loop: "{{ local_tagged_ports }}"
      
  # - name: Configure allowed vlans on {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.name }}
    # cisco.ios.ios_config:
      # parents: interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.name }}
      # lines:
      # - switchport trunk allowed vlans {{ global_allowed_vlans | join(',') }}
    # notify: "Write Config"
    # loop: "{{ local_tagged_ports }}"
      
  # - name: Configure interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.name }} as access port
    # cisco.ios.ios_config:
      # parents: interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.name }}
      # lines: interface {{ sw1_switch_interface_prefix }}{{ item }} shutdown
    # notify: "Write Config"
    # loop: "{{ local_untagged_ports ] }}"
      
  # - name: Admin shut interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.name }}
    # cisco.ios.ios_config:
      # parents: interface {{ vars[ inventory_hostname+'_switch_interface_prefix' ] }}{{ item.name }}
      # lines: "{{ global_untagged_port_conf }} + {{ item.port_conf + [item.desc] }}"
    # notify: "Write Config"
    # loop: "{{ vars[ inventory_hostname+'_interfaces' ] }}"
  - name: get the sw_untagged_ports content
    debug:
      msg: "sw_untagged_ports content: {{ vars[ inventory_hostname+'_untagged_ports' ] }}"
  - name: get the sw_untagged_ports type
    debug:
      msg: "sw_untagged_ports type: {{ vars[ inventory_hostname+'_untagged_ports' ] | type_debug }}"
  - name: get the local_untagged_ports content
    debug:
      msg: "local_tagged_ports: {{ local_tagged_ports ] }}"
  - name: get the local_tagged_ports type
    debug:
      msg: "local_tagged_ports type: {{ local_tagged_ports ] | type_debug }}"
